# .pages.yml
name: "astro-movies-cms"
framework: "astro"
rootDirectory: "./"
buildCommand: "npm install && npm run build"
outputDirectory: "dist"
installCommand: "npm install"
nodeVersion: "22.16.0"
environment:
  ASTRO_PUBLIC_BASE_URL: "/"
  NODE_ENV: "production"
staticAssets:
  - "public"
  - "content"
ignore:
  - "node_modules"
  - ".git"
  - ".cache"
plugins:
  - name: "tailwindcss" # إذا كنت تستخدم Tailwind
  - name: "vite"
routes:
  - path: "/movies/:slug"
    type: "static"
    collection: "movies"
  - path: "/series/:slug"
    type: "static"
    collection: "series"
  - path: "/series/:seriesSlug/episode/:slug"
    type: "static"
    collection: "episodes"
  - path: "/*"
    type: "static"
